[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = [
    "npm install",
    "cd client && npm install",
    "cd server && npm install"
]

[phases.build]
cmds = [
    "cd client && npm run build",
    "cd server && npm run build"
]

[start]
cmd = "cd server && npm start"
